includes:
- dynamic-plugins.default.yaml
plugins:
- disabled: false
  package: oci://${SANDBOX_PLUGIN_IMAGE}!red-hat-developer-hub-backstage-plugin-sandbox
  pluginConfig:
    dynamicPlugins:
      frontend:
        default.main-menu-items:
          menuItems:
            default.home:
              title: Home
              icon: homeIcon
              to: '/'
              priority: 200
            default.activities:
              title: Activities
              icon: activitiesIcon
              to: '/activities'
              priority: 100
            default.catalog:
              title: ""
            default.apis:
              title: ""
            default.learning-path:
              title: ""
            default.create:
              title: ""
        red-hat-developer-hub.backstage-plugin-sandbox:
          signInPage:
            importName: RHSSOSignInPage
          appIcons:
            - name: homeIcon
              importName: SandboxHomeIcon
            - name: activitiesIcon
              importName: SandboxActivitiesIcon
          dynamicRoutes:
            - path: /
              importName: SandboxPage
            - path: /activities
              importName: SandboxActivitiesPage

# Global Header
- package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-global-header
  disabled: false
  pluginConfig:
    dynamicPlugins:
      frontend:
        red-hat-developer-hub.backstage-plugin-global-header:
          mountPoints:
            - mountPoint: application/header
              importName: GlobalHeader
              config:
                position: above-main-content
            - mountPoint: global.header/component
              importName: Spacer
              config:
                priority: 99
                props:
                  growFactor: 1
                  minWidth: 1
            - mountPoint: global.header/component
              importName: ProfileDropdown
              config:
                priority: 10
            - mountPoint: global.header/profile
              importName: MenuItemLink
              config:
                priority: 100
                props:
                  title: Settings
                  link: /settings
                  icon: manageAccounts
            - mountPoint: global.header/profile
              importName: LogoutButton
              config:
                priority: 10


# Techdocs
- package: ./dynamic-plugins/dist/backstage-plugin-techdocs-backend-dynamic
  disabled: true

- package: ./dynamic-plugins/dist/backstage-plugin-techdocs
  disabled: true

- package: ./dynamic-plugins/dist/backstage-plugin-techdocs-module-addons-contrib
  disabled: true

- package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-dynamic-home-page
  disabled: true