apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: install-aikit-operator
objects:
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: aikit-operator
    namespace: ${INTEL_NAMESPACE}
  spec:
    channel: alpha
    installPlanApproval: Automatic
    name: aikit-operator
    source: certified-operators
    sourceNamespace: openshift-marketplace
parameters:
- name: INTEL_NAMESPACE
  value: openshift-operators
