apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: install-camel-k-operator
objects:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: ${CAMEL_K_OPERATOR_NAMESPACE}
  - apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: camel-k-operator
      namespace: ${CAMEL_K_OPERATOR_NAMESPACE}
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: camel-k-operator-subscription
      namespace: ${CAMEL_K_OPERATOR_NAMESPACE}
    spec:
      channel: stable
      installPlanApproval: Automatic
      name: camel-k
      source: community-operators
      sourceNamespace: openshift-marketplace
      config:
        env:
        - name: KAMEL_OPERATOR_ID
          value: "camel-k"
parameters:
  - name: CAMEL_K_OPERATOR_NAMESPACE
    value: camel-k-operator