apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: install-cluster-logging-operator
objects:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: ${LOGGING_NAMESPACE}
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    namespace: ${LOGGING_NAMESPACE}
    name: cluster-logging
    labels:
      operators.coreos.com/cluster-logging.openshift-logging: ""
  spec:
    channel: stable
    installPlanApproval: Automatic
    name: cluster-logging
    source: redhat-operators
    sourceNamespace: openshift-marketplace

- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    namespace: ${LOGGING_NAMESPACE}
    name: openshift-logging
  spec:
    targetNamespaces:
    - ${LOGGING_NAMESPACE}

parameters:
- name: LOGGING_NAMESPACE
  value: openshift-logging