apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: install-gitops-primer-operator
objects:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: gitops-primer-system
  - apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: gitops-primer
      namespace: ${GITOPS_PRIMER_OPERATOR_NAMESPACE}
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: gitops-primer-operator-subscription
      namespace: ${GITOPS_PRIMER_OPERATOR_NAMESPACE}
    spec:
      channel: alpha
      installPlanApproval: Automatic
      name: gitops-primer
      source: community-operators
      sourceNamespace: openshift-marketplace
parameters:
  - name: GITOPS_PRIMER_OPERATOR_NAMESPACE
    value: gitops-primer-system
