apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: install-image-puller-operator
objects:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: ${IMAGE_PULLER_NAMESPACE}
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: kubernetes-imagepuller-operator
    namespace: ${IMAGE_PULLER_NAMESPACE}
  spec:
    channel: stable
    installPlanApproval: Automatic
    name: kubernetes-imagepuller-operator
    source: community-operators
    sourceNamespace: openshift-marketplace
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: kubernetes-imagepuller-operator
    namespace: ${IMAGE_PULLER_NAMESPACE}
parameters:
- name: IMAGE_PULLER_NAMESPACE
  value: image-puller
