apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: install-kiali-operator
objects:
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: kiali-ossm
      namespace: ${KIALI_NAMESPACE}
    spec:
      channel: stable
      installPlanApproval: Automatic
      name: kiali-ossm
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      startingCSV: kiali-operator.v1.24.5
parameters:
  - name: KIALI_NAMESPACE
    value: openshift-operators
