# OSD comes with an operator that creates CSVs in all namespaces so kiali is being used in this case to mimic the behaviour on OCP clusters
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: install-kiali-operator
objects:
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: kiali-ossm
      namespace: ${KIALI_NAMESPACE}
    spec:
      channel: stable
      installPlanApproval: Automatic
      name: kiali-ossm
      source: redhat-operators
      sourceNamespace: openshift-marketplace
parameters:
  - name: KIALI_NAMESPACE
    value: openshift-operators
