apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: install-rhoas-operator
objects:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: rhoas-operator
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: rhoas-group
    namespace: ${RHOAS_NAMESPACE}
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: rhoas-operator
    namespace: ${RHOAS_NAMESPACE}
  spec:
    channel: beta
    installPlanApproval: Automatic
    name: rhoas-operator
    source: community-operators
    sourceNamespace: openshift-marketplace
    startingCSV: rhoas-operator.0.7.10
parameters:
- name: RHOAS_NAMESPACE
  value: rhoas-operator
