apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: install-web-terminal-operator
objects:
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: web-terminal
      namespace: ${WTO_NAMESPACE}
    spec:
      channel: fast
      installPlanApproval: Automatic
      name: web-terminal
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      startingCSV: web-terminal.v1.4.0
parameters:
  - name: WTO_NAMESPACE
    value: openshift-operators
