apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: install-toolchain-member-operator
objects:
- apiVersion: operators.coreos.com/v1alpha1
  kind: CatalogSource
  metadata:
    labels:
      opsrc-provider: codeready-toolchain
    name: dev-sandbox-member
    namespace: ${SANDBOX_NAMESPACE}
  spec:
    displayName: Dev Sandbox Operators
    image: quay.io/codeready-toolchain/member-operator-index:latest
    sourceType: grpc
    updateStrategy:
      registryPoll:
        interval: 5m0s
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: dev-sandbox-member
    namespace: ${SANDBOX_NAMESPACE}
  spec:
    targetNamespaces:
    - ${SANDBOX_NAMESPACE}
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: dev-sandbox-member
    namespace: ${SANDBOX_NAMESPACE}
  spec:
    channel: staging
    installPlanApproval: Automatic
    name: toolchain-member-operator
    source: dev-sandbox-member
    sourceNamespace: ${SANDBOX_NAMESPACE}
parameters:
- name: SANDBOX_NAMESPACE
  value: toolchain-member-operator
