apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: appstudio-env
objects:
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      openshift.io/description: ${SPACE_NAME}
      openshift.io/display-name: ${SPACE_NAME}
      openshift.io/requester: ${SPACE_NAME}
    labels:
      name: ${SPACE_NAME}-env
      argocd.argoproj.io/managed-by: gitops-service-argocd
      # billing labels ref: https://github.com/redhat-appstudio/book/blob/main/ADR/0010-namespace-metadata.md
      appstudio.redhat.com/workspace_name: ${SPACE_NAME}
    # The ${SPACE_NAME} here is actually the space (aka workspace) name that is going to be provisioned as environment sub-space (aka sub-workspace).
    # It's a legacy parameter that needs to be renamed
    # related story https://issues.redhat.com/browse/CRT-1766
    name: ${SPACE_NAME}-env

# ServiceAccount to be used by the deployer (eg. ArgoCD) to manage the content of the namespace
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    namespace: ${SPACE_NAME}-env
    name: namespace-manager

- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: additional-argocd-read
    namespace: ${SPACE_NAME}-env
  rules:
  - apiGroups:
    - authorization.openshift.io
    - rbac.authorization.k8s.io
    resources:
    - roles
    verbs:
    - view
    - list
    - watch
  - apiGroups:
    - networking.k8s.io
    resources:
    - ingressclasses
    verbs:
    - view
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - persistentvolumes
    verbs:
    - view
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: additional-argocd-read
    namespace: ${SPACE_NAME}-env
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: additional-argocd-read
  subjects:
  - kind: ServiceAccount
    name: namespace-manager

- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: namespace-manager
    namespace: ${SPACE_NAME}-env
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
  - kind: ServiceAccount
    name: namespace-manager

# Quotas and default limits for not-terminating containers (regular long-running containers)
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: compute-deploy
    namespace: ${SPACE_NAME}-env
  spec:
    scopes:
    - NotTerminating
    hard:
      limits.cpu: "20"
      limits.memory: ${MEMORY_LIMIT}
      requests.cpu: 1750m
      requests.memory: ${MEMORY_REQUEST}
# and terminating (short-lived containers like build) containers
# since builds are not supposed to be created in an environment namespace, then the limits are set to zero
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: compute-build
    namespace: ${SPACE_NAME}-env
  spec:
    scopes:
    - Terminating
    hard:
      cpu: 0
      memory: 0
      pods: 0
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: storage
    namespace: ${SPACE_NAME}-env
  spec:
    hard:
      limits.ephemeral-storage: 50Gi
      requests.storage: 50Gi
      requests.ephemeral-storage: 50Gi
      count/persistentvolumeclaims: "12"
- apiVersion: v1
  kind: LimitRange
  metadata:
    name: resource-limits
    namespace: ${SPACE_NAME}-env
  spec:
    limits:
    - type: "Container"
      default:
        cpu: 2000m
        memory: 2Gi
      defaultRequest:
        cpu: 10m
        memory: 256Mi

- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-same-namespace
    namespace: ${SPACE_NAME}-env
  spec:
    podSelector: {}
    ingress:
    - from:
      - podSelector: {}
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-from-openshift-ingress
    namespace: ${SPACE_NAME}-env
  spec:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            network.openshift.io/policy-group: ingress
    podSelector: {}
    policyTypes:
    - Ingress
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-from-openshift-monitoring
    namespace: ${SPACE_NAME}-env
  spec:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            network.openshift.io/policy-group: monitoring
    podSelector: {}
    policyTypes:
    - Ingress
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-from-codeready-workspaces-operator
    namespace: ${SPACE_NAME}-env
  spec:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            network.openshift.io/policy-group: codeready-workspaces
    podSelector: {}
    policyTypes:
    - Ingress
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-from-olm-namespaces
    namespace: ${SPACE_NAME}-env
  spec:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            openshift.io/scc: anyuid
    podSelector: {}
    policyTypes:
    - Ingress
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-from-console-namespaces
    namespace: ${SPACE_NAME}-env
  spec:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            network.openshift.io/policy-group: console
    podSelector: {}
    policyTypes:
    - Ingress
parameters:
- name: SPACE_NAME
  required: true
- name: MEMORY_LIMIT
  value: "32Gi"
- name: MEMORY_REQUEST
  value: "32Gi"
- name: MEMORY_BUILD_LIMIT
  value: "64Gi"
- name: MEMORY_BUILD_REQUEST
  value: "32Gi"
