apiVersion: toolchain.dev.openshift.com/v1alpha1
kind: ToolchainConfig
metadata:
  name: config
spec:
  host:
    automaticApproval:
      enabled: true
  members:
    default:
      autoscaler:
        deploy: false
      memberStatus:
        refreshPeriod: "1s"
      toolchainCluster:
        healthCheckPeriod: "5s"
