apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: default-network-policies
objects:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      labels:
        provider: sandbox-sre
      name: allow-from-same-namespace
      namespace: ${NAMESPACE}
    spec:
      ingress:
      - from:
        - podSelector: {}
      podSelector: {}
      policyTypes:
      - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      labels:
        provider: sandbox-sre
      name: allow-from-ingress
      namespace: ${NAMESPACE}
    spec:
      ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
      podSelector: {}
      policyTypes:
      - Ingress
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      labels:
        provider: sandbox-sre
      name: allow-from-openshift-customer-monitoring-namespace
      namespace: ${NAMESPACE}
    spec:
      ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-customer-monitoring
      podSelector: {}
      policyTypes:
      - Ingress
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      labels:
        provider: sandbox-sre
      name: allow-from-openshift-operator-lifecycle-manager-namespace
      namespace: ${NAMESPACE}
    spec:
      ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-operator-lifecycle-manager
      podSelector: {}
      policyTypes:
      - Ingress
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      labels:
        provider: sandbox-sre
      name: allow-from-openshift-logging-namespace
      namespace: ${NAMESPACE}
    spec:
      ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-logging
      podSelector: {}
      policyTypes:
      - Ingress

parameters:
- name: NAMESPACE