apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-accounts.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

generatorOptions:
  disableNameSuffixHash: true
