apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-accounts.yaml
  - deployment.yaml
  - dynamic-plugins-root-pvc.yaml
  - service.yaml
  - route.yaml
  - toolchainconfig.yaml
  - oauth-idp.yaml

generatorOptions:
  disableNameSuffixHash: true
