apiVersion: v1
kind: Secret
metadata:
  name: openid-sandbox-public-client-secret
  namespace: openshift-config
type: Opaque
stringData:
  clientSecret: dummy
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - mappingMethod: claim
      name: openid
      openID:
        claims:
          email:
            - email
          name:
            - username
          preferredUsername:
            - preferred_username
        clientID: sandbox-public
        clientSecret:
          name: openid-sandbox-public-client-secret
        issuer: "https://sso.devsandbox.dev/auth/realms/sandbox-dev"
      type: OpenID
