apiVersion: v1
kind: Namespace
metadata:
  name: openshift-jobset-system
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: jobset-operator-group
  namespace: openshift-jobset-system
spec:
  targetNamespaces:
  - openshift-jobset-system
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: job-set
  namespace: openshift-jobset-system
spec:
  channel: stable-v1.0
  name: job-set
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
