apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: appstudio-cluster-resources
objects:
- apiVersion: quota.openshift.io/v1
  kind: ClusterResourceQuota
  metadata:
    name: for-${SPACE_NAME}-deployments
  spec:
    quota:
      hard:
        count/deployments.apps: ${{DEPLOYMENT_QUOTA}}
        count/deploymentconfigs.apps: ${{DEPLOYMENT_QUOTA}}
        count/pods: ${{POD_QUOTA}}
    selector:
      annotations: null
      labels:
        matchLabels:
          toolchain.dev.openshift.com/space: ${SPACE_NAME}
- apiVersion: quota.openshift.io/v1
  kind: ClusterResourceQuota
  metadata:
    name: for-${SPACE_NAME}-replicas
  spec:
    quota:
      hard:
        count/replicasets.apps: ${{REPLICASET_QUOTA}}
        count/replicationcontrollers: ${{REPLICASET_QUOTA}}
    selector:
      annotations: null
      labels:
        matchLabels:
          toolchain.dev.openshift.com/space: ${SPACE_NAME}
- apiVersion: quota.openshift.io/v1
  kind: ClusterResourceQuota
  metadata:
    name: for-${SPACE_NAME}-routes
  spec:
    quota:
      hard:
        count/ingresses.extensions: ${{ROUTE_QUOTA}}
        count/routes.route.openshift.io: ${{ROUTE_QUOTA}}
    selector:
      annotations: null
      labels:
        matchLabels:
          toolchain.dev.openshift.com/space: ${SPACE_NAME}
- apiVersion: quota.openshift.io/v1
  kind: ClusterResourceQuota
  metadata:
    name: for-${SPACE_NAME}-jobs
  spec:
    quota:
      hard:
        count/jobs.batch: "30"
        count/daemonsets.apps: "30"
        count/cronjobs.batch: "30"
        count/statefulsets.apps: "30"
    selector:
      annotations: null
      labels:
        matchLabels:
          toolchain.dev.openshift.com/space: ${SPACE_NAME}
- apiVersion: quota.openshift.io/v1
  kind: ClusterResourceQuota
  metadata:
    name: for-${SPACE_NAME}-services
  spec:
    quota:
      hard:
        count/services: ${{SERVICE_QUOTA}}
    selector:
      annotations: null
      labels:
        matchLabels:
          toolchain.dev.openshift.com/space: ${SPACE_NAME}
- apiVersion: quota.openshift.io/v1
  kind: ClusterResourceQuota
  metadata:
    name: for-${SPACE_NAME}-bc
  spec:
    quota:
      hard:
        count/buildconfigs.build.openshift.io: "30"
    selector:
      annotations: null
      labels:
        matchLabels:
          toolchain.dev.openshift.com/space: ${SPACE_NAME}
- apiVersion: quota.openshift.io/v1
  kind: ClusterResourceQuota
  metadata:
    name: for-${SPACE_NAME}-secrets
  spec:
    quota:
      hard:
        count/secrets: ${{SECRET_QUOTA}}
    selector:
      annotations: null
      labels:
        matchLabels:
          toolchain.dev.openshift.com/space: ${SPACE_NAME}
- apiVersion: quota.openshift.io/v1
  kind: ClusterResourceQuota
  metadata:
    name: for-${SPACE_NAME}-cm
  spec:
    quota:
      hard:
        count/configmaps: ${{CONFIGMAP_QUOTA}}
    selector:
      annotations: null
      labels:
        matchLabels:
          toolchain.dev.openshift.com/space: ${SPACE_NAME}
- apiVersion: toolchain.dev.openshift.com/v1alpha1
  kind: Idler
  metadata:
    name: ${SPACE_NAME}
  spec:
    timeoutSeconds: ${{IDLER_TIMEOUT_SECONDS}}
parameters:
- name: SPACE_NAME
  required: true
- name: IDLER_TIMEOUT_SECONDS
  # No Idling
  value: "0"
# Quota
- name: REPLICASET_QUOTA
  value: "30"
- name: DEPLOYMENT_QUOTA
  value: "30"
- name: POD_QUOTA
  value: "600"
- name: ROUTE_QUOTA
  value: "30"
- name: SERVICE_QUOTA
  value: "30"
- name: CONFIGMAP_QUOTA
  value: "100"
- name: SECRET_QUOTA
  value: "300"
