FROM registry.access.redhat.com/ubi7-dev-preview/ubi-minimal:latest

LABEL maintainer "Devtools <devtools@redhat.com>"
LABEL author "Devtools <devtools@redhat.com>"

ENV OPERATOR=/usr/local/bin/host-operator \
    USER_UID=1001 \
    USER_NAME=host-operator \
    LANG=en_US.utf8

# install operator binary
COPY host-operator ${OPERATOR}

USER ${USER_UID}

ENTRYPOINT [ "/usr/local/bin/host-operator" ]
